export const QUESTIONS = [
  "Who are your competitors?",
  "What is your product?",
  "What is your business model?",
  "What do customers say about your product?",
  "Who uses your product?",
  "What do customers use your product for?",
  "How do you get to $100 million in ARR?",
  "How do you differentiate from the incumbents? (OpenAI, Microsoft, HuggingFace, Co-pilot)",
  "How do you know people want this?",
  "What is your unfair advantage?",
  "What do you understand about your business that others don't?",
  "What do you understand about your users?",
  "Why will you succeed?",
  "Why did you pick this idea to work on?",
  "What is the next step with the product evolution?",
  "Who needs what you're making?",
  "Who is the team?",
  "What problem are you solving?",
  "How do you know it’s a real problem?",
  "Why should we invest?",
  "How do we know your team will stick together?",
  "What has surprised you about user behaviour?",
  "What is your distribution strategy?",
  "How will you get users?",
  "What problems/hurdles are you anticipating?",
  "What domain expertise do you have?",
  "How will customers and/or users find out about you?",
  "Who are your competitors?",
  "What are the top things users want?",
  "Where else can the company grow into into?",
  "What's new about what you make?",
  "How did your team meet?",
  "What will you do if we don't fund you?",
  "Who might become competitors?",
  "Why did you choose this idea?",
  "What is your burn rate?",
  "Why will you succeed?",
  "How many users are paying?",
  "How does your product work in more detail?",
  "How are you meeting customers?",
  "What, exactly, makes you different from existing options?",
  "How long can you go before funding?",
  "How big an opportunity is there?",
  "What metrics do you track daily, weekly, and monthly?",
  "Have there been any substantial pivots in your business strategy? If so, why?",
  "How do you handle internal conflicts within the team?",
  "Describe your ideal customer.",
  "How do you handle the potential misuse of your AI technology?",
  "What keeps you up at night regarding your business?",
  "What's the equity split among the founders? How did you decide on that split?",
  "If there were one area where you could use external help or expertise, what would it be?",
  "What questions do you have for us?",
  "What are you looking for in an investor?",
  "What culture are you trying to build?",
  "What are the goals for the next 6 months?",
  "What is the long term vision of the company?",
  "What are the specifics of your short term product roadmap?",
  "How much are you looking to raise?",
  "What is your current burn rate?",
  "What is your current ARR?",
  "How much are you raising?",
  "You’re raising at an $x cap? How did you come up with that number?",
  "Why are you only raising $x? That seems like not enough to get you to your Series A, and it may not be a big enough round for a fund of our size.",
  "Do you have any questions for us?",
  "Who else has invested?",
  "Are you looking for a lead investor?",
  "Who will be your next hire?",
  "Who else are you talking to?", // trick question: DO NOT ANSWER
  "What are you looking for in an investor/partner?",
  "What is your market size?",
  "How do you think about defensibility / why can’t your competitors copy this?",
  "What’s your moat?",
  "What questions should I have asked you that I didn’t?",
  "How are you different than [your biggest competitor]?",
  "Tell me about your competitive landscape.",
  "What’s your GTM strategy?",
  "How are you thinking about spending the money you raise (and how this will affect your burn)? How long will it last you?",
  "What hires are you planning to make first?",
  "Who would you hire or how would you add to your team?",
  "What's your exit strategy?",
  "Why are you a solo founder?",
  "What are the biggest challenges you expect to have in the future? What would be a reason you may not succeed in building a billion $ business? If you fail, what will be the main reason?",
  "What keeps you up at night?",
  "What’s your short term product roadmap look like, and what does the product look like 5-10 years from now?",
  "What is the top reason customers say no to buying your product?",
  "How would your ideal investor support you?",
];

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = array.slice(); // Make a shallow copy to avoid modifying the original array

  for(let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]; // Swap elements
  }

  return shuffled;
}

export const getQuestions = () => shuffleArray(QUESTIONS);