export const QUESTIONS = [
  "Who are your competitors?",
  "What is your product?",
  "What is your business model?",
  "What do customers say about your product?",
  "What do customers use your product for?",
  "How do you get to $100 million in ARR?",
  "How do you differentiate from the incumbents? (OpenAI, Microsoft, HuggingFace, Co-pilot)",
  "How do you know people want this?",
  "How did your team get together?",
  "What is your unfair advantage?",
  "What do you understand about your business that others don't?",
  "What do you understand about your users?",
  "Why will you succeed?",
  "Why did you pick this idea to work on?",
  "What is the next step with the product evolution?",
  "Who needs what you're making?",
  "How do we know your team will stick together?",
  "What is your distribution strategy?",
  "How will you get users?",
  "What problems/hurdles are you anticipating?",
  "Who would you hire or how would you add to your team?",
  "What domain expertise do you have?",
  "How will customers and/or users find out about you?",
];